### ISSUE TITLE
Plugin not load

### ISSUE THREAD

**Issue by Cavas17** [kaszito/homebridge-eedomus#1]
Hi,

I have an issue with this plugin.

![capture d ecran 2016-03-17 a 19 53 44](https://cloud.githubusercontent.com/assets/17765433/13858042/118ec058-ec7d-11e5-8374-abb800f0fa3b.png)

I try to solve it in change '/home/pi/.homebridge/config.json' by the correct path : '/utilisateurs/Florent/.hombridge/config.json' because I work on Mac OS X but it didn't work...

![capture d ecran 2016-03-17 a 20 14 04](https://cloud.githubusercontent.com/assets/17765433/13858132/8513c8a2-ec7d-11e5-8156-1780095d0d06.png)

Anyone have an idee please ?
Thanks

PS : I'm a noob and sorry for my broken English, I'm a French user.

**Comment by kaszito** [comment]
You have to edit my index.js file and change this line (number 5):

`eedomus_config = '/home/pi/.homebridge/config.json';`

for this one: 

`eedomus_config = '/utilisateurs/Florent/.hombridge/config.json';`

Try and let me know. I made this plugin and tested it only in Raspberry with Raspbian Jessie. 

I'm a total n00b with js, so I don't know how can I do this automatically.

**Comment by Cavas17** [comment]
Thanks for answer,

I try to change the line 5 by

`eedomus_config = '/utilisateurs/Florent/.hombridge/config.json';`

But I think there is an error at the word hombridge so I correct it by

`eedomus_config = '/utilisateurs/Florent/.homebridge/config.json';`

But It didn't work

![capture d ecran 2016-03-18 a 17 40 08](https://cloud.githubusercontent.com/assets/17765433/13885006/cc5da7ce-ed30-11e5-977d-ab198f19a7f7.png)

However I'm sure this is the correct path.
When I do that : 

![capture d ecran 2016-03-18 a 17 39 30](https://cloud.githubusercontent.com/assets/17765433/13885025/e5e99fb8-ed30-11e5-93a6-c3bf7d574acc.png)

Finder open this window : 

![capture d ecran 2016-03-18 a 17 39 36](https://cloud.githubusercontent.com/assets/17765433/13885028/ea9843de-ed30-11e5-8681-42ec5b9371da.png)

**Comment by kaszito** [comment]
What about permissions in config.json?

Your error log seems to be clear: "no such file or directory".

Could you try opening a Terminal in your Mac and typing: "`ls -lrt /utilisateurs/Florent/.homebridge/config.json`"?

Have you add this part in your config.json?

```
  "credentials": {
       "ip" : "your_local_eedomus_ip",
       "api_user" : "your_eedomus_api_user",
       "api_secret" : "your_eedomus_api_secret"
   },
```

**Comment by Cavas17** [comment]
Okay I finally understood what's wrong. That was a translation issue. I had to change "utilisateurs" by "users". So the correct path is

 `/users/Florent/.homebridge/config.json`

Sorry and thanks a lot for help.
